### ISSUE TITLE
https://registry.yarnpkg.com/sch%20%20%20%20eduled-event-emitter: Not found

### ISSUE THREAD

**Issue by st-clair-clarke** [seppevs/scheduled-event-emitter#73]
Hi, am attempting to install scheduled-event-emitter using yarn package manager.

Each attempt results in the following error

```

error An unexpected error occurred: "https://registry.yarnpkg.com/sch%20%20%20%20eduled-event-emitter: 
Not found".info If you think this is a bug, please open a bug report with the information provided in "~\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

```

Actual log error message:

```

Yarn version: 
  1.22.5

Node version: 
  14.8.0

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/sch%20%20%20%20eduled-event-emitter: Not found
      at Request.params.callback [as _callback] (C:\Users\ST. CLAIR CLARKE\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:66988:18)
      at Request.self.callback (C:\Users\ST. CLAIR CLARKE\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:140662:22)
      at Request.emit (events.js:314:20)
      at Request.<anonymous> (C:\Users\ST. CLAIR CLARKE\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:141634:10)
      at Request.emit (events.js:314:20)
      at IncomingMessage.<anonymous> (C:\Users\ST. CLAIR CLARKE\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:141556:12)
      at Object.onceWrapper (events.js:420:28)
      at IncomingMessage.emit (events.js:326:22)
      at endReadableNT (_stream_readable.js:1244:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

```

It appears that what should be  "https://registry.yarnpkg.com/scheeduled-event-emitter is actually  "https://registry.yarnpkg.com/sch%20%20%20%20eduled-event-emitter.

Could please check for me. I cannot install, remove or do anything because of this error.

Thanks

**Comment by st-clair-clarke** [comment]
My problem - some spaces were inadvertently inserted in my package.json file. Sorry.
